### ISSUE TITLE
Changes required to work on 6.7

### ISSUE THREAD

**Issue by SimonFair** [coppit/unraid-snmp#4]
I had to make changes to snmp.plg file for it to work on reboot version changed to 5.8 and the pkghost and md5 needed to be changed.

 

<!DOCTYPE PLUGIN [
<!ENTITY name        "snmp">
<!ENTITY author      "coppit">
<!ENTITY version     "2018.07.22">
<!ENTITY pluginURL   "https://github.com/coppit/unraid-snmp/raw/master/snmp.plg">
<!ENTITY pkgversion  "5.8">
<!ENTITY gitURL      "https://raw.githubusercontent.com/&author;/unraid-snmp/master">
<!ENTITY plugdir     "/usr/local/emhttp/plugins/&name;">
<!ENTITY pkgdir      "/boot/packages">
<!ENTITY cfgdir      "/boot/config/plugins/&name;">
<!ENTITY pkghost     "https://mirrors.slackware.com/slackware/slackware64-current/slackware64/n/">

<!ENTITY snmppkg     "net-snmp-&pkgversion;-x86_64-4.txz">
<!ENTITY snmppkgmd5  "119ecee76951c11d782f077c7a89826e">

<!ENTITY libnlpkg    "libnl-1.1.4-x86_64-1.txz">
<!ENTITY libnlpkgmd5 "435837a5bf0401a937d6ec93e458333b">

<!ENTITY iconfile    "snmp.png">
<!ENTITY iconfilemd5 "863e97dc0e59ae9352f558ee8e0d40a2">

<!ENTITY community   "public">
<!ENTITY location    "Here">
<!ENTITY contact     "root@tower">
]>

**Comment by kubedzero** [comment]
addressed in https://github.com/coppit/unraid-snmp/issues/5 , if you want to take a look!
